-- Sanitized reference schema for a stateful conversational AI product.
-- This is not a direct export of the private Flectos production database.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  monthly_income numeric(14,2),
  monthly_spending_limit numeric(14,2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.conversation_states (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  current_flow text,
  flow_step integer,
  flow_data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.financial_events (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  event_type text not null check (event_type in ('expense', 'income')),
  amount numeric(14,2) not null check (amount > 0),
  category text,
  description text,
  event_date date not null default current_date,
  payment_method text,
  installments integer check (installments is null or installments > 0),
  planned boolean,
  emotional_context text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.decision_events (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  item text,
  amount numeric(14,2) check (amount is null or amount > 0),
  origin text,
  risk_level text check (risk_level is null or risk_level in ('low', 'medium', 'high')),
  decision text check (
    decision is null or decision in (
      'wait_24h',
      'find_alternative',
      'buy_consciously',
      'save_decision',
      'give_up'
    )
  ),
  context jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.recent_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null check (role in ('user', 'assistant', 'system')),
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.behavioral_signals (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  signal_key text not null,
  signal_value jsonb not null,
  confidence numeric(5,4) check (confidence is null or (confidence >= 0 and confidence <= 1)),
  observed_at timestamptz not null default now(),
  expires_at timestamptz
);

create table if not exists public.ai_incidents (
  id uuid primary key default gen_random_uuid(),
  fingerprint text not null,
  severity text not null check (severity in ('low', 'medium', 'high', 'urgent')),
  component text not null,
  error_code text,
  summary text not null,
  context jsonb not null default '{}'::jsonb,
  status text not null default 'open' check (status in ('open', 'investigating', 'resolved')),
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  occurrence_count integer not null default 1 check (occurrence_count > 0)
);
